"""
Ingest: normalize every input into a .docx so there is ONE redaction path.

  - .docx  : used as-is (full-fidelity round-trip).
  - .pdf   : text extracted into a NEW plain .docx (layout is intentionally NOT
             preserved). Image-only/scanned PDFs are rejected.
  - image  : screenshots/photos are OCR'd on-device (Apple Vision) into text,
             then a NEW plain .docx. Output is redacted text, not a redacted
             image. The image never leaves the machine.
  - text   : pasted text becomes a plain .docx (and we can also return the
             redacted text directly).

Producing a .docx for every input means the run-fragmentation engine, the
validation sweep, and restore all work uniformly.
"""

from __future__ import annotations

import os
import shutil
from typing import List

from docx import Document


class IngestError(Exception):
    pass


def _blank_identity(doc) -> None:
    """Clear python-docx's default property stamps (creator='python-docx',
    description='generated by python-docx'). For the paste/PDF path these are
    our own artifacts, not the user's data, and would otherwise add noise to
    detection."""
    cp = doc.core_properties
    cp.author = ""
    cp.last_modified_by = ""
    cp.title = ""
    cp.subject = ""
    cp.keywords = ""
    cp.comments = ""  # dc:description


def text_to_docx(text: str, output_path: str) -> str:
    doc = Document()
    _blank_identity(doc)
    for line in text.split("\n"):
        doc.add_paragraph(line)
    doc.save(output_path)
    return output_path


def pdf_to_docx(pdf_path: str, output_path: str) -> str:
    try:
        import pdfplumber  # type: ignore
    except Exception as e:  # pragma: no cover
        raise IngestError("PDF support needs pdfplumber (pip install pdfplumber).") from e

    lines: List[str] = []
    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            extracted = page.extract_text() or ""
            if extracted:
                lines.extend(extracted.split("\n"))

    if not "".join(lines).strip():
        raise IngestError(
            "This PDF has no extractable text; it looks scanned or image-only. "
            "Dactful v1 does not OCR. Export a text-based PDF or a .docx instead."
        )

    doc = Document()
    _blank_identity(doc)
    for line in lines:
        doc.add_paragraph(line)
    doc.save(output_path)
    return output_path


def prepare_input(src_path: str, kind: str, work_dir: str) -> str:
    """Return a path to a .docx ready for the redaction engine.

    kind: "docx" | "pdf" | "text" (for text, src_path holds the raw string).
    """
    out = os.path.join(work_dir, "input.docx")
    if kind == "docx":
        # Copy into the session workspace so the session owns a stable file
        # (the caller's uploaded temp file may be deleted right after).
        shutil.copy(src_path, out)
        return out
    if kind == "pdf":
        return pdf_to_docx(src_path, out)
    if kind == "image":
        return image_to_docx(src_path, out)
    if kind == "text":
        return text_to_docx(src_path, out)
    raise IngestError(f"Unsupported input kind: {kind}")


def image_to_docx(image_path: str, output_path: str) -> str:
    from .ocr import OcrError, OcrUnavailable, image_to_text

    try:
        text = image_to_text(image_path)
    except OcrUnavailable as e:
        raise IngestError(str(e)) from e
    except OcrError as e:
        raise IngestError(str(e)) from e

    if not text.strip():
        raise IngestError(
            "No text was found in that image. If it's a photo, try a sharper, "
            "straight-on screenshot with clear text."
        )
    return text_to_docx(text, output_path)
